### ISSUE TITLE
Add compilation functionality to CI server

### ISSUE THREAD

**Issue by amarhod** [amarhod/smallest-java-ci#6]
The CI server supports compiling. Compilation is triggered by a webhook, the CI server compiles the branch where the change has been made, as specified in the HTTP payload.

**Comment by GustavDowling** [comment]
Our current solution show's what we want to do and one way to do it. Still in experimental phase since no tests for it yet and it shouldn't be hard-coded what repo to watch and where on the servers PC to clone the repo into and build.
